Add check for non-existing tag in release build
There is a button in the CI web interface to trigger a release in
"normal" commit and PR builds. Add a guard to ensure that the tag the
build is supposed to release exists, to avoid potential for partially
failed releases triggered manually by mistake on non-tag builds.

diff --git a/bin/make_release b/bin/make_release
--- a/bin/make_release
+++ b/bin/make_release
@@ -78,9 +78,14 @@ if [[ "${CI:-false}" != "true" ]]; then
     exit 1
 fi
 
+if ! git rev-parse --quiet --tags "refs/tags/${RELEASE}" &> /dev/null; then
+    echo "git tag ${RELEASE} does not exist, can't create release";
+    exit 2
+fi
+
 if gh release view "$RELEASE" &> /dev/null; then
     echo "The github release $RELEASE already exists, can't overwrite a existing release"
-    exit 2
+    exit 3
 fi
 
 # get release notes from the content of the annotated release tag
